config/routes.rb
Mysecurity::Application.routes.draw do
  resources :situacion_revista

  resources :establecimientos

  resources :estado_civils

  resources :tipo_documentos

  resources :sexos

  resources :regions

  resources :personas

  resources :nivels

  resources :localidads

  resources :role_permissions

    devise_for :users, :path => 'user'

    resources :roles
    resources :users
  

  root :to => "establecimientos#index"

end

app/models/ability.rb
class Ability
 
  include CanCan::Ability
 
  def initialize(user)
    user ||= User.new # guest user
    unless user.nil?
	    if user.role? :admin
	      can :manage, :all
	      #can :update, User do |user2|
	      #  user2.try(:id) == user.id
	      #end    
	    elsif user.role? :user
	      can :manage, [Persona]
	    end    
    end    
    #can :create, [Persona]
  end
end

app/models/establecimiento.rb
class Establecimiento < ActiveRecord::Base
  attr_accessible :ambito, :anexo, :codigo_jurisdiccional, :cue, :cue_anexo, :domicilio, :localidad_id, :nombre, :sector

  belongs_to :localidad

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/estado_civil.rb
class EstadoCivil < ActiveRecord::Base
  attr_accessible :nombre

  has_many :persona

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/localidad.rb
class Localidad < ActiveRecord::Base
  attr_accessible :cp, :nombre, :region_id

  has_many :establecimiento
  has_many :persona
  belongs_to :region

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/nivel.rb
class Nivel < ActiveRecord::Base
  attr_accessible :nombre

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/persona.rb
class Persona < ActiveRecord::Base
  attr_accessible :apellidos, :calle, :depto, :estado_civil_id, :fecha_nacimiento, :localidad_id, :nombres, :nro_calle, :nro_documento, :piso, :sexo_id, :tipo_documento_id
  attr_accessible :situacion_revista_id,:telefono_contacto, :email

  belongs_to :tipo_documento
  belongs_to :localidad
  belongs_to :estado_civil
  belongs_to :sexo
  belongs_to :situacion_revistum

  validates :nombres, :presence => true
  validates :apellidos, :presence => true
  validates :nro_documento, :presence => true

  def to_s
  	"#{ self.nombres } + #{ self.apellidos }"
  end

end

app/models/region.rb
class Region < ActiveRecord::Base
  attr_accessible :nombre

  has_many :localidad

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :role_children, :foreign_key => 'parent_id', :class_name => 'RoleRole'
  has_many :children, :through => :role_children
  
  has_many :role_parents, :foreign_key => 'role_id', :class_name => 'RoleRole'
  has_many :parents, :through => :role_parents

  has_many :permissions, :foreign_key => 'role_id', :class_name => 'RolePermission'


end

app/models/role_permission.rb
class RolePermission < ActiveRecord::Base
end

app/models/role_role.rb
class RoleRole < ActiveRecord::Base
  belongs_to :parent, :foreign_key => 'parent_id', :class_name => 'Role'
  belongs_to :child, :foreign_key => 'role_id', :class_name => 'Role'  
end

app/models/sexo.rb
class Sexo < ActiveRecord::Base
  attr_accessible :nombre

  has_many :persona

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/tipo_documento.rb
class TipoDocumento < ActiveRecord::Base
  attr_accessible :nombre

  has_many :persona

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_roles, :foreign_key => 'user_id', :class_name => 'UserRole'
  has_many :roles, :through => :user_roles
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role_ids, :apellidos, :nombres

  def to_s
    "#{ self.nombres } + #{ self.apellidos }"
  end


  def role?(role)
    return !!self.roles.find_by_description(role.to_s.camelize)
  end

end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  belongs_to :user, :foreign_key => 'user_id', :class_name => 'User'
  belongs_to :role, :foreign_key => 'role_id', :class_name => 'Role'
end

app/models/util.rb
class Util < ActiveRecord::Base
  # attr_accessible :title, :body

  def self.fecha_a_cadena(fecha)
  	if fecha then
  		return I18n.l fecha, :format => fecha.day.to_s + " de %B de " + fecha.year.to_s 
  	else
  		return "" 
  	end
  end

  def self.fecha_a_es(fecha)
  	if fecha then
  		return I18n.l fecha
  	else
  		return ""
  	end  	
  end

end

app/controllers/establecimientos_controller.rb
class EstablecimientosController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /establecimientos
  # GET /establecimientos.json
  def index
    @establecimientos = Establecimiento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @establecimientos }
    end
  end

  # GET /establecimientos/1
  # GET /establecimientos/1.json
  def show
    @establecimiento = Establecimiento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @establecimiento }
    end
  end

  # GET /establecimientos/new
  # GET /establecimientos/new.json
  def new
    @establecimiento = Establecimiento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @establecimiento }
    end
  end

  # GET /establecimientos/1/edit
  def edit
    @establecimiento = Establecimiento.find(params[:id])
  end

  # POST /establecimientos
  # POST /establecimientos.json
  def create
    @establecimiento = Establecimiento.new(params[:establecimiento])

    respond_to do |format|
      if @establecimiento.save
        format.html { redirect_to @establecimiento, notice: 'Establecimiento was successfully created.' }
        format.json { render json: @establecimiento, status: :created, location: @establecimiento }
      else
        format.html { render action: "new" }
        format.json { render json: @establecimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /establecimientos/1
  # PUT /establecimientos/1.json
  def update
    @establecimiento = Establecimiento.find(params[:id])

    respond_to do |format|
      if @establecimiento.update_attributes(params[:establecimiento])
        format.html { redirect_to @establecimiento, notice: 'Establecimiento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @establecimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /establecimientos/1
  # DELETE /establecimientos/1.json
  def destroy
    @establecimiento = Establecimiento.find(params[:id])
    @establecimiento.destroy

    respond_to do |format|
      format.html { redirect_to establecimientos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/establecimientos_helper.rb
module EstablecimientosHelper
end

app/helpers/nivels_helper.rb
module NivelsHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper

  def build_role_list(partialFile='')
    list_items = ""
    roleList = Role.find_by_sql("SELECT * FROM roles WHERE id NOT IN (SELECT role_id FROM role_roles)")
    for role in roleList
      list_items += build_role_list_item(role ,partialFile)
    end
    output = list_items
    return output.html_safe
  end

  def build_role_list_item(local_role,partialFile)
    local_children=""
    if local_role.children.length > 0
      child_output = ""
      for child in local_role.children
        child_output += build_role_list_item(child,partialFile)
      end
      local_children += render :partial => '/roles/ul', :locals => { :list_items => child_output.html_safe }
    end
    output = render( :partial => partialFile, :locals => {:the_children => local_children.html_safe,:current_role => local_role})
    return output.html_safe
  end

end

app/helpers/sexos_helper.rb
module SexosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/establecimientos/_form.html.erb
<%= form_for @establecimiento, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :codigo_jurisdiccional, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :codigo_jurisdiccional, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cue, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :cue, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :anexo, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :anexo, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cue_anexo, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :cue_anexo, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sector, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sector, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :ambito, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ambito, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :localidad_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select(:localidad_id, Localidad.all, :id, :nombre) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :domicilio, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :domicilio, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                establecimientos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/establecimientos/edit.html.erb
<%- model_class = Establecimiento -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/establecimientos/index.html.erb
<%- model_class = Establecimiento -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table id="tabla-establecimientos" class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:codigo_jurisdiccional) %></th>
      <th><%= model_class.human_attribute_name(:cue) %></th>
      <th><%= model_class.human_attribute_name(:anexo) %></th>
      <th><%= model_class.human_attribute_name(:cue_anexo) %></th>
      <th><%= model_class.human_attribute_name(:sector) %></th>
      <th><%= model_class.human_attribute_name(:ambito) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:localidad_id) %></th>
      <th><%= model_class.human_attribute_name(:domicilio) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @establecimientos.each do |establecimiento| %>
      <tr>
        <td><%= establecimiento.codigo_jurisdiccional %></td>
        <td><%= establecimiento.cue %></td>
        <td><%= establecimiento.anexo %></td>
        <td><%= establecimiento.cue_anexo %></td>
        <td><%= establecimiento.sector %></td>
        <td><%= establecimiento.ambito %></td>
        <td><%= establecimiento.nombre %></td>
        <td><%= establecimiento.localidad %></td>
        <td><%= establecimiento.domicilio %></td>
        <td>
          <div class="btn-group pull-right">
            <a class="btn dropdown-toggle btn-primary" data-toggle="dropdown" href="#">
              Acciones
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Ver', establecimiento %></li>
              <li><%= link_to 'Editar', edit_establecimiento_path(establecimiento) %></li>
              <li><%= link_to 'Eliminar', establecimiento, method: :delete, data: { confirm: 'Seguro desea eliminar?' } %></li>
              </li>
            </ul>
          </div>
        </td>       
      </tr>
    <% end %>
  </tbody>
</table>

<!--<div class="row">
  <input id ="busqueda-cj" type="text" placeholder="Buscar Codigo Jurisdiccional" />
</div>
-->

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_establecimiento_path,
            :class => 'btn btn-primary' %>


<script type="text/javascript">
    $(document).ready(function($) {

     
      //var title = $('#tabla-establecimientos thead th').eq(0).text();
      //$('<input type="text" placeholder="Buscar '+title+'" />').after('#tabla-establecimientos');
      
      //var title = $('#tabla-establecimientos thead th').eq(0).text();
      

      var pepe = $('#tabla-establecimientos').dataTable({
        "sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
        "sPaginationType": "bootstrap",
        "aoColumnDefs": [
          { "bSearchable": false, "aTargets": [ 9 ] }
        ],
        "oLanguage": {
              "sUrl": "language.es.json",
          },
          "aaSorting": [[ 0, "desc" ]],
      });

      //$("#busqueda-cj").on( 'keyup change', function () {
      //  pepe
      //      .column( $(this).parent().index()+':visible' )
      //      .search( this.value )
      //      .draw();
      //} );

    });
</script>

app/views/establecimientos/new.html.erb
<%- model_class = Establecimiento -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/establecimientos/show.html.erb
<%- model_class = Establecimiento -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:codigo_jurisdiccional) %>:</strong></dt>
  <dd><%= @establecimiento.codigo_jurisdiccional %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cue) %>:</strong></dt>
  <dd><%= @establecimiento.cue %></dd>
  <dt><strong><%= model_class.human_attribute_name(:anexo) %>:</strong></dt>
  <dd><%= @establecimiento.anexo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cue_anexo) %>:</strong></dt>
  <dd><%= @establecimiento.cue_anexo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sector) %>:</strong></dt>
  <dd><%= @establecimiento.sector %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ambito) %>:</strong></dt>
  <dd><%= @establecimiento.ambito %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @establecimiento.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:localidad_id) %>:</strong></dt>
  <dd><%= @establecimiento.localidad %></dd>
  <dt><strong><%= model_class.human_attribute_name(:domicilio) %>:</strong></dt>
  <dd><%= @establecimiento.domicilio %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              establecimientos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_establecimiento_path(@establecimiento), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              establecimiento_path(@establecimiento),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>