config/routes.rb
Mysecurity::Application.routes.draw do
  resources :situacion_revista

  resources :establecimientos

  resources :estado_civils

  resources :tipo_documentos

  resources :sexos

  resources :regions

  resources :personas

  resources :nivels

  resources :localidads

  resources :role_permissions

    devise_for :users, :path => 'user'

    resources :roles
    resources :users
  

  root :to => "establecimientos#index"

end

app/models/ability.rb
class Ability
 
  include CanCan::Ability
 
  def initialize(user)
    user ||= User.new # guest user
    unless user.nil?
	    if user.role? :admin
	      can :manage, :all
	      #can :update, User do |user2|
	      #  user2.try(:id) == user.id
	      #end    
	    elsif user.role? :user
	      can :manage, [Persona]
	    end    
    end    
    #can :create, [Persona]
  end
end

app/models/establecimiento.rb
class Establecimiento < ActiveRecord::Base
  attr_accessible :ambito, :anexo, :codigo_jurisdiccional, :cue, :cue_anexo, :domicilio, :localidad_id, :nombre, :sector

  belongs_to :localidad

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/estado_civil.rb
class EstadoCivil < ActiveRecord::Base
  attr_accessible :nombre

  has_many :persona

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/localidad.rb
class Localidad < ActiveRecord::Base
  attr_accessible :cp, :nombre, :region_id

  has_many :establecimiento
  has_many :persona
  belongs_to :region

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/nivel.rb
class Nivel < ActiveRecord::Base
  attr_accessible :nombre

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/persona.rb
class Persona < ActiveRecord::Base
  attr_accessible :apellidos, :calle, :depto, :estado_civil_id, :fecha_nacimiento, :localidad_id, :nombres, :nro_calle, :nro_documento, :piso, :sexo_id, :tipo_documento_id
  attr_accessible :situacion_revista_id,:telefono_contacto, :email

  belongs_to :tipo_documento
  belongs_to :localidad
  belongs_to :estado_civil
  belongs_to :sexo
  belongs_to :situacion_revistum

  validates :nombres, :presence => true
  validates :apellidos, :presence => true
  validates :nro_documento, :presence => true

  def to_s
  	"#{ self.nombres } + #{ self.apellidos }"
  end

end

app/models/region.rb
class Region < ActiveRecord::Base
  attr_accessible :nombre

  has_many :localidad

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :role_children, :foreign_key => 'parent_id', :class_name => 'RoleRole'
  has_many :children, :through => :role_children
  
  has_many :role_parents, :foreign_key => 'role_id', :class_name => 'RoleRole'
  has_many :parents, :through => :role_parents

  has_many :permissions, :foreign_key => 'role_id', :class_name => 'RolePermission'


end

app/models/role_permission.rb
class RolePermission < ActiveRecord::Base
end

app/models/role_role.rb
class RoleRole < ActiveRecord::Base
  belongs_to :parent, :foreign_key => 'parent_id', :class_name => 'Role'
  belongs_to :child, :foreign_key => 'role_id', :class_name => 'Role'  
end

app/models/sexo.rb
class Sexo < ActiveRecord::Base
  attr_accessible :nombre

  has_many :persona

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/tipo_documento.rb
class TipoDocumento < ActiveRecord::Base
  attr_accessible :nombre

  has_many :persona

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_roles, :foreign_key => 'user_id', :class_name => 'UserRole'
  has_many :roles, :through => :user_roles
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role_ids, :apellidos, :nombres

  def to_s
    "#{ self.nombres } + #{ self.apellidos }"
  end


  def role?(role)
    return !!self.roles.find_by_description(role.to_s.camelize)
  end

end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  belongs_to :user, :foreign_key => 'user_id', :class_name => 'User'
  belongs_to :role, :foreign_key => 'role_id', :class_name => 'Role'
end

app/models/util.rb
class Util < ActiveRecord::Base
  # attr_accessible :title, :body

  def self.fecha_a_cadena(fecha)
  	if fecha then
  		return I18n.l fecha, :format => fecha.day.to_s + " de %B de " + fecha.year.to_s 
  	else
  		return "" 
  	end
  end

  def self.fecha_a_es(fecha)
  	if fecha then
  		return I18n.l fecha
  	else
  		return ""
  	end  	
  end

end

app/controllers/nivels_controller.rb
class NivelsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /nivels
  # GET /nivels.json
  def index
    @nivels = Nivel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nivels }
    end
  end

  # GET /nivels/1
  # GET /nivels/1.json
  def show
    @nivel = Nivel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nivel }
    end
  end

  # GET /nivels/new
  # GET /nivels/new.json
  def new
    @nivel = Nivel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nivel }
    end
  end

  # GET /nivels/1/edit
  def edit
    @nivel = Nivel.find(params[:id])
  end

  # POST /nivels
  # POST /nivels.json
  def create
    @nivel = Nivel.new(params[:nivel])

    respond_to do |format|
      if @nivel.save
        format.html { redirect_to @nivel, notice: 'Nivel was successfully created.' }
        format.json { render json: @nivel, status: :created, location: @nivel }
      else
        format.html { render action: "new" }
        format.json { render json: @nivel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nivels/1
  # PUT /nivels/1.json
  def update
    @nivel = Nivel.find(params[:id])

    respond_to do |format|
      if @nivel.update_attributes(params[:nivel])
        format.html { redirect_to @nivel, notice: 'Nivel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nivel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nivels/1
  # DELETE /nivels/1.json
  def destroy
    @nivel = Nivel.find(params[:id])
    @nivel.destroy

    respond_to do |format|
      format.html { redirect_to nivels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/localidads_helper.rb
module LocalidadsHelper
end

app/helpers/nivels_helper.rb
module NivelsHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper

  def build_role_list(partialFile='')
    list_items = ""
    roleList = Role.find_by_sql("SELECT * FROM roles WHERE id NOT IN (SELECT role_id FROM role_roles)")
    for role in roleList
      list_items += build_role_list_item(role ,partialFile)
    end
    output = list_items
    return output.html_safe
  end

  def build_role_list_item(local_role,partialFile)
    local_children=""
    if local_role.children.length > 0
      child_output = ""
      for child in local_role.children
        child_output += build_role_list_item(child,partialFile)
      end
      local_children += render :partial => '/roles/ul', :locals => { :list_items => child_output.html_safe }
    end
    output = render( :partial => partialFile, :locals => {:the_children => local_children.html_safe,:current_role => local_role})
    return output.html_safe
  end

end

app/helpers/sexos_helper.rb
module SexosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/nivels/_form.html.erb
<%= form_for @nivel, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                nivels_path, :class => 'btn' %>
  </div>
<% end %>

app/views/nivels/edit.html.erb
<%- model_class = Nivel -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/nivels/index.html.erb
<%- model_class = Nivel -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Niveles" %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @nivels.each do |nivel| %>
      <tr>
        <td><%= link_to nivel.id, nivel_path(nivel) %></td>
        <td><%= nivel.nombre %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_nivel_path(nivel), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      nivel_path(nivel),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_nivel_path,
            :class => 'btn btn-primary' %>

app/views/nivels/new.html.erb
<%- model_class = Nivel -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/nivels/show.html.erb
<%- model_class = Nivel -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @nivel.nombre %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              nivels_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_nivel_path(@nivel), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              nivel_path(@nivel),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>