config/routes.rb
Mysecurity::Application.routes.draw do
  resources :situacion_revista

  resources :establecimientos

  resources :estado_civils

  resources :tipo_documentos

  resources :sexos

  resources :regions

  resources :personas

  resources :nivels

  resources :localidads

  resources :role_permissions

    devise_for :users, :path => 'user'

    resources :roles
    resources :users
  

  root :to => "establecimientos#index"

end

app/models/role_permission.rb
class RolePermission < ActiveRecord::Base
end

app/controllers/role_permissions_controller.rb
class RolePermissionsController < ApplicationController
  layout nil
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /role_permissions
  # GET /role_permissions.json



  def index
    index_helper

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @role_permissions }
    end
  end

  # GET /role_permissions/1
  # GET /role_permissions/1.json
  def show
    @role_permission = RolePermission.find(params[:id])
    #authorize! :show, @role_permission
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role_permission }
    end
  end

  # GET /role_permissions/new
  # GET /role_permissions/new.json



  def new
    prepare
    @role_permission = RolePermission.new
    @role_permission.role_id = params[:role_id]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role_permission }
    end
  end

  # GET /role_permissions/1/edit
  def edit
    prepare
    @role_permission = RolePermission.find(params[:id])
  end

  # POST /role_permissions
  # POST /role_permissions.json
  def create
    @role_permission = RolePermission.new(params[:role_permission])

    respond_to do |format|
      if @role_permission.save
        format.html { 
          index_helper
          render :action => 'index'
        }
        format.json { render json: @role_permission, status: :created, location: @role_permission }
      else
        format.html { render action: "new" }
        format.json { render json: @role_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /role_permissions/1
  # PUT /role_permissions/1.json
  def update
    @role_permission = RolePermission.find(params[:id])

    respond_to do |format|
      if @role_permission.update_attributes(params[:role_permission])
        format.html {
          index_helper
          render :action => 'index'
        }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @role_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /role_permissions/1
  # DELETE /role_permissions/1.json
  def destroy
    @role_permission = RolePermission.find(params[:id])
    @role_permission.destroy

    respond_to do |format|
      format.html {
        index_helper
        render :action => 'index'
      }
      format.json { head :ok }
    end
  end


  private :prepare
end

app/helpers/role_permissions_helper.rb
module RolePermissionsHelper

  def index_helper
    if params[:role_id].nil?
      if params[:role_permission][:role_id].nil?
        log_error " role_id parameter is invalid!"
      else
        @the_role_id = params[:role_permission][:role_id]
      end
    else
      @the_role_id = params[:role_id]
    end

    begin
      @role_permissions = RolePermission.find(:all,:conditions => ["role_id=?",@the_role_id])
    rescue ActiveRecord::RecordNotFound
      log_error "record not found role_id=" + params[:role_id]
    end
  end

  def prepare
    Rails.application.eager_load!
    @roles = Role.all
    @regulators = get_models
    @conducts = get_actions
  end

  def get_models
    regulators = Array.new
    ActiveRecord::Base.descendants.each{ |model|
      regulators[regulators.length] = model.name
    }
    return regulators
  end

  def get_actions
    conducts = Array.new
    ApplicationController.descendants.each { |regulator|
      the_actions = regulator.action_methods
      the_actions.each {|the_action|
        conducts[conducts.length] = the_action
      }
    }
    return conducts
  end
end

app/views/role_permissions/_form.html.erb
<%= form_for(@role_permission) do |f| %>
  <% if @role_permission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role_permission.errors.count, "error") %> prohibited this role_permission from being saved:</h2>

      <ul>
      <% @role_permission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :role_id %>
  </div>
  <div class="field">
    <%= f.label 'Controller' %><br />
    <%= collection_select(:role_permission, :regulator, @regulators, :to_s, :to_s)  %>
  </div>
  <div class="field">
    <%= f.label 'Action' %><br />
    <%= collection_select(:role_permission, :conduct, @conducts, :to_s, :to_s) %>
  </div>
  <div class="actions">
    <%= f.submit  (action_name.upcase == 'EDIT' ? 'Update' : 'Add') + " Permission", :class => "ajaxSubmit" %>
  </div>
<% end %>

app/views/role_permissions/_javascript.html.erb
<script>

  $(".deleteLink").click(function(event){
    event.preventDefault();
    $.post(event.target, 
    "_method=DELETE",
    function(data) {
      writePermission(data);
    },
    'html');
  });


  $('.ajaxLink').click(function(event){
    event.preventDefault(); // Prevent link from following its href
    fillPermission(event.target);
    return false;
  });

  $('.standardSubmit').click(function(event){
    event.preventDefault(); // Prevent link from following its href
    submitFormPost(event.target.form,
      function(data) {
        writePermission(data);
      }
    );
  });



</script>

app/views/role_permissions/edit.html.erb
<h3>Edit Permission</h1>

<%= render 'form' %>

<%= link_to 'Show', @role_permission, :class => 'ajaxLink' %> |
<%= link_to 'Back', role_permissions_path(:role_id => @role_permission.role_id), :class => 'ajaxLink' %>
<%= render 'javascript' %>

app/views/role_permissions/index.html.erb
<table class="showTableBorder">
  <tr>
    <th class="firstCell">Model</th>
    <th class="lastCell">Action</th>
    <th class="lastCell firstCell" colspan="3"></th>
  </tr>
  <%  @role_permissions.each do |role_permission| %>
    <tr>
      <td class="firstCell"><%= role_permission.regulator %></td>
      <td class="middleCell"><%= role_permission.conduct %></td>
      <td class="middleCell"><%= link_to 'Show', role_permission, :class => 'ajaxLink' %></td>
      <td class="middleCell"><%= link_to 'Edit', edit_role_permission_path(role_permission), :class => 'ajaxLink' %></td>
      <td class="lastCell"><%= link_to 'Destroy', role_permission_path(role_permission,:role_id => role_permission.role_id), :class => 'ajaxDeleteLink' %></td>
    </tr>
  <%   end %>
</table>

<br />

<%= link_to 'New Role permission', new_role_permission_path(:role_id => @the_role_id), :class => 'ajaxLink' %>

app/views/role_permissions/new.html.erb
<h3>New Permission</h3>

<%= render 'form' %>

<%= link_to 'Back', role_permissions_path(:role_id => params[:role_id]), :class => 'ajaxLink' %>

app/views/role_permissions/show.html.erb
<h3>Show Permission</h3>
<p>
  <b>Regulator:</b>
  <%= @role_permission.regulator %>
</p>

<p>
  <b>Conduct:</b>
  <%= @role_permission.conduct %>
</p>


<%= link_to 'Edit', edit_role_permission_path(@role_permission), :class => 'ajaxLink' %> |
<%= link_to 'Back', role_permissions_path(:role_id => @role_permission.role_id), :class => 'ajaxLink' %>