config/routes.rb
Mysecurity::Application.routes.draw do
  resources :situacion_revista

  resources :establecimientos

  resources :estado_civils

  resources :tipo_documentos

  resources :sexos

  resources :regions

  resources :personas

  resources :nivels

  resources :localidads

  resources :role_permissions

    devise_for :users, :path => 'user'

    resources :roles
    resources :users
  

  root :to => "establecimientos#index"

end

app/models/ability.rb
class Ability
 
  include CanCan::Ability
 
  def initialize(user)
    user ||= User.new # guest user
    unless user.nil?
	    if user.role? :admin
	      can :manage, :all
	      #can :update, User do |user2|
	      #  user2.try(:id) == user.id
	      #end    
	    elsif user.role? :user
	      can :manage, [Persona]
	    end    
    end    
    #can :create, [Persona]
  end
end

app/models/establecimiento.rb
class Establecimiento < ActiveRecord::Base
  attr_accessible :ambito, :anexo, :codigo_jurisdiccional, :cue, :cue_anexo, :domicilio, :localidad_id, :nombre, :sector

  belongs_to :localidad

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/estado_civil.rb
class EstadoCivil < ActiveRecord::Base
  attr_accessible :nombre

  has_many :persona

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/localidad.rb
class Localidad < ActiveRecord::Base
  attr_accessible :cp, :nombre, :region_id

  has_many :establecimiento
  has_many :persona
  belongs_to :region

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/nivel.rb
class Nivel < ActiveRecord::Base
  attr_accessible :nombre

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/persona.rb
class Persona < ActiveRecord::Base
  attr_accessible :apellidos, :calle, :depto, :estado_civil_id, :fecha_nacimiento, :localidad_id, :nombres, :nro_calle, :nro_documento, :piso, :sexo_id, :tipo_documento_id
  attr_accessible :situacion_revista_id,:telefono_contacto, :email

  belongs_to :tipo_documento
  belongs_to :localidad
  belongs_to :estado_civil
  belongs_to :sexo
  belongs_to :situacion_revistum

  validates :nombres, :presence => true
  validates :apellidos, :presence => true
  validates :nro_documento, :presence => true

  def to_s
  	"#{ self.nombres } + #{ self.apellidos }"
  end

end

app/models/region.rb
class Region < ActiveRecord::Base
  attr_accessible :nombre

  has_many :localidad

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :role_children, :foreign_key => 'parent_id', :class_name => 'RoleRole'
  has_many :children, :through => :role_children
  
  has_many :role_parents, :foreign_key => 'role_id', :class_name => 'RoleRole'
  has_many :parents, :through => :role_parents

  has_many :permissions, :foreign_key => 'role_id', :class_name => 'RolePermission'


end

app/models/role_permission.rb
class RolePermission < ActiveRecord::Base
end

app/models/role_role.rb
class RoleRole < ActiveRecord::Base
  belongs_to :parent, :foreign_key => 'parent_id', :class_name => 'Role'
  belongs_to :child, :foreign_key => 'role_id', :class_name => 'Role'  
end

app/models/sexo.rb
class Sexo < ActiveRecord::Base
  attr_accessible :nombre

  has_many :persona

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/tipo_documento.rb
class TipoDocumento < ActiveRecord::Base
  attr_accessible :nombre

  has_many :persona

  def to_s
  	"#{ self.nombre }"
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_roles, :foreign_key => 'user_id', :class_name => 'UserRole'
  has_many :roles, :through => :user_roles
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role_ids, :apellidos, :nombres

  def to_s
    "#{ self.nombres } + #{ self.apellidos }"
  end


  def role?(role)
    return !!self.roles.find_by_description(role.to_s.camelize)
  end

end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  belongs_to :user, :foreign_key => 'user_id', :class_name => 'User'
  belongs_to :role, :foreign_key => 'role_id', :class_name => 'Role'
end

app/models/util.rb
class Util < ActiveRecord::Base
  # attr_accessible :title, :body

  def self.fecha_a_cadena(fecha)
  	if fecha then
  		return I18n.l fecha, :format => fecha.day.to_s + " de %B de " + fecha.year.to_s 
  	else
  		return "" 
  	end
  end

  def self.fecha_a_es(fecha)
  	if fecha then
  		return I18n.l fecha
  	else
  		return ""
  	end  	
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])
    authorize! :show, @role

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render json: @role, status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :ok }
    end
  end
end

app/helpers/localidads_helper.rb
module LocalidadsHelper
end

app/helpers/nivels_helper.rb
module NivelsHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper

  def build_role_list(partialFile='')
    list_items = ""
    roleList = Role.find_by_sql("SELECT * FROM roles WHERE id NOT IN (SELECT role_id FROM role_roles)")
    for role in roleList
      list_items += build_role_list_item(role ,partialFile)
    end
    output = list_items
    return output.html_safe
  end

  def build_role_list_item(local_role,partialFile)
    local_children=""
    if local_role.children.length > 0
      child_output = ""
      for child in local_role.children
        child_output += build_role_list_item(child,partialFile)
      end
      local_children += render :partial => '/roles/ul', :locals => { :list_items => child_output.html_safe }
    end
    output = render( :partial => partialFile, :locals => {:the_children => local_children.html_safe,:current_role => local_role})
    return output.html_safe
  end

end

app/helpers/sexos_helper.rb
module SexosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/roles/_children_checkbox.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<li><%= check_box_tag "role[child_ids][]", current_role.id, @role.children.include?(current_role), :disabled => current_role.eql?(@role) %><%= current_role.description %></li><%= the_children %>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label 'Parents' %><br />
    <%=  build_role_list('parents_checkbox') %>
  </div>
  <div class="field">
    <%= f.label 'Children' %><br />
    <%=  build_role_list('children_checkbox') %>
  </div>
  <div class="actions">
    <%= f.submit :id => 'standardSubmit' %>
  </div>
<% end %>

app/views/roles/_indexrow.erb
  <li>
    <span class="roleDescription"><%= current_role.description %></span>
    <span class="roleCommands">[<%= link_to 'Show', current_role %> -
    <%= link_to 'Edit', edit_role_path(current_role) %> -
    <%= link_to 'Destroy', current_role, confirm: 'Seguro desea eliminar?', method: :delete %>]
    </span>
  </li>
  <%= the_children %>

app/views/roles/_parents_checkbox.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<li><%= check_box_tag "role[parent_ids][]", current_role.id, @role.parents.include?(current_role), :disabled => current_role.eql?(@role) %><%= current_role.description %></li><%= the_children %>

app/views/roles/_ul.html.erb
<ul class="bob">
  <%= list_items %>
</ul>

app/views/roles/edit.html.erb
<script>
  $(document).ready(function(){
    defaultLocation();
  });

  function defaultLocation() {
    fillAjaxHolder('/role_permissions?role_id=<%= @role.id %>');
  }
</script>


<h1>Editing role</h1>

<%= render 'form' %>



<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

<h2>Permissions</h2>
<div id="ajaxHolder">

</div>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<%= link_to 'New Role', new_role_path %>
<br />
<ul>
  <li class="listNoDecorate">
    <span class="roleDescription">Role Name</span>
    <span class="roleCommands">[Commands]</span>
  </li>

  <%=  build_role_list('indexrow') %>
</ul>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @role.description %>
</p>


<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>